name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag alifeee/steamcollageapi:latest
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker push
      run: docker push alifeee/steamcollageapi:latest
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          docker stop steamcollageapi
          docker rm steamcollageapi
          docker pull alifeee/steamcollageapi
          docker run -d -p 5000:5000 -e API_KEY=${{ secrets.STEAM_API_KEY }} --name steamcollageapi alifeee/steamcollageapi
          docker ps -a

