name: ThunderClientTesting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: "16.x"
    - name: Install Thunder Client CLI
      run: |
        npm install -g @thunderclient/cli
    - name: Make directory for results
      run: mkdir -p thunder-reports
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests
      run: |
        python ./api/api.py &
        sleep 2
        tc --env test --col tests --stop-on-fail --report html,xml
        kill -9 `lsof -i:5000 -t`
      env:
        API_KEY: ${{ secrets.API_KEY }}
    - name: Output the run Details
      uses: actions/upload-artifact@v3
      with:
        name: RunReports
        path: thunder-reports
        
